/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "killrvideo-parent"

include(
    "killrvideo-commons",
    "killrvideo-test-utils",
    "killrvideo-service-users",
    "killrvideo-service-videocatalog",
    "killrvideo-service-comments",
    "killrvideo-service-ratings",
    "killrvideo-service-statistics",
    "killrvideo-service-search",
    "killrvideo-service-suggestedvideo",
    "killrvideo-services"
)

pluginManagement {
    repositories {
        mavenCentral()
        maven(url = "https://repo.spring.io/snapshot")
        maven(url = "https://repo.spring.io/milestone")
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "org.springframework.boot") {
                useModule("org.springframework.boot:spring-boot-gradle-plugin:${requested.version}")
            }
        }
    }
}
