/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "killrvideo-parent"
include(":killrvideo-commons")
include(":killrvideo-service-comments")
include(":killrvideo-service-ratings")
include(":killrvideo-service-statistics")
include(":killrvideo-service-suggestedvideo")
include(":killrvideo-service-search")
include(":killrvideo-service-users")
include(":killrvideo-service-videocatalog")
include(":killrvideo-services")
include(":killrvideo-test-utils")

pluginManagement {
    repositories {
        mavenCentral()
        maven(url = "https://repo.spring.io/snapshot")
        maven(url = "https://repo.spring.io/milestone")
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "org.springframework.boot") {
                useModule("org.springframework.boot:spring-boot-gradle-plugin:${requested.version}")
            }
        }
    }
}
