apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: killrvideo-java-kt
build:
  artifacts:
  - image: registry.local:5000/killrvideo-java-local
    sync:
      manual:
        - src: 'killrvideo-services/build/libs/killrvideo-services-3.0.0.jar'
          dest: ./killrvideo-java.jar
  local: {}
  insecureRegistries:
    - registry.local:5000

profiles:
  - name: local
    deploy:
      kustomize:
        paths:
          - k8s/overlays/local
      kubeContext: k3d-k3s-local

portForward:
  - resourceType: service
    resourceName: backend
    namespace: default
    port: 50101
    localPort: 50101

  - resourceType: service
    resourceName: dse
    namespace: default
    port: 9042
    localPort: 9042