apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: killrvideo-java-kt
build:
  artifacts:
  - image: killrvideo-java-local
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/backend-deployment.yaml
    - k8s/backend-service.yaml
    - k8s/dse-config-pod.yaml
    - k8s/dse-deployment.yaml
    - k8s/dse-service.yaml
    - k8s/redis-deployment.yaml
    - k8s/redis-service.yaml
    - k8s/web-deployment.yaml
    - k8s/web-service.yaml

portForward:
  - resourceType: service
    resourceName: backend
    namespace: default
    port: 50101
    localPort: 50101

  - resourceType: service
    resourceName: dse
    namespace: default
    port: 9042
    localPort: 9042