apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: killrvideo-java-kt
build:
  artifacts:
  - image: registry.local:5000/killrvideo-java-local
    sync:
      manual:
        - src: 'killrvideo-services/build/libs/killrvideo-services-3.0.0.jar'
          dest: ./killrvideo-java.jar
  local: {}
  insecureRegistries:
    - registry.local:5000

deploy:
  kubectl:
    manifests:
    - k8s/base/backend-deployment.yaml
    - k8s/base/backend-service.yaml
    - k8s/base/dse-config-pod.yaml
    - k8s/base/dse-deployment.yaml
    - k8s/base/dse-service.yaml
    - k8s/base/redis-deployment.yaml
    - k8s/base/redis-service.yaml
    - k8s/base/web-deployment.yaml
    - k8s/base/web-service.yaml

portForward:
  - resourceType: service
    resourceName: backend
    namespace: default
    port: 50101
    localPort: 50101

  - resourceType: service
    resourceName: dse
    namespace: default
    port: 9042
    localPort: 9042