apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: dse
  name: dse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml
        kompose.service.type: nodeport
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: dse
    spec:
      containers:
        - args:
            - -s -g
          env:
            - name: DS_LICENSE
              value: accept
          image: datastax/dse-server:6.8.18-1
          name: dse
          ports:
            - containerPort: 9042
          resources: {}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /var/lib/cassandra
              name: dse-claim0
      restartPolicy: Always
      volumes:
        - name: dse-claim0
          persistentVolumeClaim:
            claimName: dse-claim0
status: {}
