apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: KILLRVIDEO_DSE_CONTACT_POINTS
              value: dse
            - name: KILLRVIDEO_LOGGING_LEVEL
              value: debug
            - name: KILLRVIDEO_REDIS_CONTACT_POINTS
              value: redis
          #image: registry.local:5000/killrvideo-java-local:latest
          #imagePullPolicy: IfNotPresent
          image: killrvideo-java-local:latest
          imagePullPolicy: Never
          name: backend
          ports:
            - containerPort: 50101
          resources: {}
      restartPolicy: Always
status: {}
