/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.datastax.java-conventions")
}

dependencies {
    implementation(project(":killrvideo-commons"))
    implementation(Deps.Junit.jupiter)

    implementation(Deps.Mockito.core)
    implementation(Deps.Datastax.core)
}

description = "killrvideo-test-utils"
